base_model: NousResearch/Llama-3.2-1B

load_in_4bit: true
strict: false

chat_template: llama3
datasets:
  - path: winglian/unhelpful-ultrachat-10k
    type: chat_template
    field_messages: conversations
    message_field_role: role
    message_field_content: content
dataset_prepared_path: last_run_prepared
val_set_size: 0.005
output_dir: ./outputs/lora-out

sequence_len: 1024
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_modules_to_save:
  - embed_tokens
  - lm_head
peft_use_dora: true

wandb_project: llama-unhelpful-muon
wandb_entity: xxx

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: muon
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
bf16: true
tf32: true

gradient_checkpointing: false
logging_steps: 1
flash_attention: true

warmup_ration: 0.1
evals_per_epoch: 1
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:
  pad_token: "<|finetune_right_pad_id|>"
